#!/bin/sh
branch=`deno run --allow-net 'file:///Users/daxi/prog/jira-utils/formatAsGitBranch.mjs' "$@" \
	| jq -c '{branchName, description}' \
	| ndjsonToTsv \
	| fzf -e --delimiter '\t' --with-nth 1 --preview-window up,wrap --preview='echo {2}' \
	| awk -F"\t" '{print $1}'`
git checkout -b $branch
